# Generated by Django 4.2.21 on 2025-05-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
        migrations.AlterModelTable(
            name='userquery',
            table='userquery',
        ),
    ]
